export const INITIALIZE_APP_FAILURE = 'INITIALIZE_APP_FAILURE';
export const INITIALIZE_APP_PAUSE = 'INITIALIZE_APP_PAUSE';
export const INITIALIZE_APP_REQUEST = 'INITIALIZE_APP_REQUEST';
export const INITIALIZE_APP_RESUME = 'INITIALIZE_APP_RESUME';
export const INITIALIZE_APP_SUCCESS = 'INITIALIZE_APP_SUCCESS';