export const AUTHENTICATION_PENDING = 'AUTHENTICATION_PENDING';
export const AUTHENTICATION_FULFILLED = 'AUTHENTICATION_FULFILLED';
export const AUTHENTICATION_REJECTED = 'AUTHENTICATION_REJECTED';
export const LOGOUT = 'USERS_LOGOUT';
