/** ***************UserRPPDetailsActions*************** */
export const USER_RPP_DETAILS_REQUEST_PENDING = 'USER_RPP_DETAILS_REQUEST_PENDING';
export const USER_RPP_DETAILS_REQUEST_FULFILLED = 'USER_RPP_DETAILS_REQUEST_FULFILLED';
export const USER_RPP_DETAILS_REQUEST_REJECTED = 'USER_RPP_DETAILS_REQUEST_REJECTED';